version: "3"

services:

  course-service:

    build: ./CourseService

    ports:

      - "8001:8000"

  student-service:

    build: ./StudentService

    ports:

      - "8002:8000"

  gateway:

    build: ./APIGateway

    ports:

      - "8000:8000"